import { Header } from "@/components/header";
import type { Metadata } from "next";
import "./globals.css";
import PageTransition from "@/components/page-transition/PageTransition";
import { ProtectedRoute } from "@/components/protected-route/ProtectedRoute";

export const metadata: Metadata = {
  title: "ScoreIt",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <ProtectedRoute>
          <PageTransition>{children}</PageTransition>
        </ProtectedRoute>
      </body>
    </html>
  );
}
