import { Header } from "@/components/header";
import type { Metadata } from "next";
import "./globals.css";
import PageTransition from "@/components/page-transition/PageTransition";
import { ProtectedRoute } from "@/components/protected-route/ProtectedRoute";
import { Toaster } from "react-hot-toast";


export const metadata: Metadata = {
  title: "ScoreIt",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />

        <Toaster
          position="top-center"
          toastOptions={{
            duration: 3000,
            style: {
              background: "#333",
              color: "#fff",
            },
          }}
        />
          {children}
        
      </body>
    </html>
  );
}
