// app/layout.tsx
import type { Metadata } from "next";
import "@/app/globals.css";
import { MemberProvider } from "@/context/MemberContext";
import { AuthProvider } from "@/context/AuthContext";
import ThemeHydration from "@/app/ThemeHydration";

export const metadata: Metadata = {
  title: "ScoreIt",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html suppressHydrationWarning>
      <head>
        <ThemeHydration />
      </head>
      <body>
        <MemberProvider>
          <AuthProvider>{children}</AuthProvider>
        </MemberProvider>
      </body>
    </html>
  );
}
