import { notFound } from "next/navigation";
import { routing, isValidLocale } from "@/i18n/routing";
import { NextIntlClientProvider } from "next-intl";
import { Header } from "@/components/header";
import { MemberProvider } from "@/context/MemberContext";
import { Toaster } from "react-hot-toast";
import type { Metadata } from "next";
import { AuthProvider } from "@/context/AuthContext"; 
import "@/app/globals.css";

export const metadata: Metadata = {
  title: "ScoreIt",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const locale = params?.locale;


  if (!isValidLocale(locale)) {
    notFound();
  }

  const messages = (await import(`@/i18n/messages/${locale}.json`)).default;

  return (
    <MemberProvider>
      <html lang={locale}>
        <body>
        <AuthProvider> 
          <NextIntlClientProvider locale={locale} messages={messages}>
            <Header />
            <Toaster
              position="top-center"
              toastOptions={{
                duration: 3000,
                style: {
                  background: "#333",
                  color: "#fff",
                },
              }}
            />
            {children}
          </NextIntlClientProvider>
        </AuthProvider>  
        </body>
      </html>
    </MemberProvider>
  );
}
