import "@/app/globals.css";
import { Header } from "@/components/header";
import { MemberProvider } from "@/context/MemberContext";
import { Toaster } from "react-hot-toast";
import type { Metadata } from "next";
import { AuthProvider } from "@/context/AuthContext";
import { IntlProvider } from "./intl-provider"; 

export const metadata: Metadata = {
  title: "ScoreIt",
  description: "Generated by create next app",
};

export default function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  return (
    <MemberProvider>
      <html lang={params.locale}>
        <body>
          <AuthProvider>
            <IntlProvider locale={params.locale}>
              <Header />
              <Toaster
                position="top-center"
                toastOptions={{
                  duration: 3000,
                  style: {
                    background: "#333",
                    color: "#fff",
                  },
                }}
              />
              {children}
            </IntlProvider>
          </AuthProvider>
        </body>
      </html>
    </MemberProvider>
  );
}
